In [2]:
# Need a function to intialize a model with given configuration
# from cs336_basics import BasicsTransformerLM
import torch
from torch import nn


In [18]:
Y = torch.randint(low=0, high=10, size=(2, 5), device="mps")
Y

tensor([[4, 9, 5, 3, 3],
        [8, 7, 3, 7, 4]], device='mps:0')

In [ ]:
import timeit

# Simple timing
time_taken = timeit.timeit('x = 2 + 2', number=1000)

# Timing a function
def my_function():
    return sum(range(100))

time_taken = timeit.timeit(my_function, number=100)

# Using Timer class
timer = timeit.Timer('x = 2 + 2')
time_taken = timer.timeit(number=1000)

# With setup code
setup = '''
import torch
x = torch.randn(1000, 1000)
'''
stmt = 'torch.mm(x, x)'
time_taken = timeit.timeit(stmt, setup, number=10)

# Using default_timer for high precision
start = timeit.default_timer()
# ... code to time ...
end = timeit.default_timer()
elapsed = end - start

In [20]:
import timeit
type(timeit.default_timer())

float

In [28]:
!uv pip install tabulate

Using Python 3.13.2 environment at: /Users/rajyadav/src/github.com/personal/basic_ml/stanford-cs336/assignment1-basics/.venv
Resolved 1 package in 538ms                                          
Installed 1 package in 8ms                                  
 + tabulate==0.9.0


In [30]:
import pandas as pd

df = pd.DataFrame([
    {"id": 1, "name": "raj"},
    {"id": 2, "name": "suraj"}
])
type(df.to_markdown())

str

In [31]:
x = torch.randn(2, 3, 4)
x

tensor([[[-1.2198,  0.6549, -1.3556, -1.4028],
         [ 2.8317, -0.0686, -0.6520, -1.0967],
         [-1.4651,  1.6015, -0.4859, -1.0580]],

        [[ 0.3800,  0.1878, -1.3283, -0.0288],
         [-0.1179, -1.0737, -2.6609, -1.3908],
         [-0.9113,  0.3218, -0.4763, -1.2071]]])

In [32]:
indices = torch.argmax(x, dim=-1) # Max along last dimension
indices

tensor([[1, 0, 1],
        [0, 0, 1]])

In [39]:
# Example with numbers:
predictions = torch.tensor([
    [0.7, 0.2, 0.1],  # Sample 1: probabilities for 3 classes
    [0.1, 0.8, 0.1]   # Sample 2: probabilities for 3 classes
])  # Shape: [2, 3]

targets = torch.tensor([0, 1])  # True class indices
# Shape: [2]

In [ ]:
targets.shape

torch.Size([2])

In [45]:
import math
(math.log(0.7) + math.log(0.8))/2

-0.2899092476264711

In [48]:
criterion = nn.CrossEntropyLoss()
loss = criterion(predictions, targets)
loss

tensor(0.7288)

In [47]:
import torch
import numpy as np

# Given:
predictions = torch.tensor([
    [0.7, 0.2, 0.1],  # Target is 0
    [0.1, 0.8, 0.1]   # Target is 1
])
targets = torch.tensor([0, 1])

# Manual Cross Entropy Calculation:
# Loss = -1/N * Σ log(p_correct)

# 1. Take log of probabilities
log_probs = torch.log(predictions)
# [[-0.3567, -1.6094, -2.3026],
#  [-2.3026, -0.2231, -2.3026]]

# 2. Select log prob of correct class for each sample
correct_log_probs = [
    log_probs[0][0],  # -0.3567 (log(0.7))
    log_probs[1][1]   # -0.2231 (log(0.8))
]

# 3. Calculate mean negative log probability
loss = -torch.mean(torch.tensor(correct_log_probs))
# = -(-0.3567 + -0.2231)/2
# ≈ 0.2899

# Verify with PyTorch:
criterion = torch.nn.CrossEntropyLoss()
torch_loss = criterion(predictions, targets, )
print(f"Manual loss: {loss:.4f}")
print(f"PyTorch loss: {torch_loss:.4f}")

Manual loss: 0.2899
PyTorch loss: 0.7288


In [49]:
import torch

# [batch, seq_len, vocab]
logits = torch.tensor([
    [   # Example 1 in batch
        [2.2, 0.1, 1.5, 0.3, 0.5],    # Token 1
        [1.1, 1.0, 0.5, 0.2, 0.2],    # Token 2
        [0.9, 2.2, 0.1, 0.4, 1.5],    # Token 3
        [0.3, 0.3, 0.1, 3.2, 0.1]     # Token 4
    ],
    [   # Example 2 in batch
        [0.7,  2.0, 0.3, 0.1, 0.1],   # Token 1
        [1.5,  0.2, 3.0, 0.1, 0.7],   # Token 2
        [0.2,  0.3, 0.1, 1.8, 2.5],   # Token 3
        [2.1,  0.2, 0.2, 0.3, 0.9]    # Token 4
    ]
])  # shape: [2, 4, 5]



In [54]:
from einops import einsum, rearrange
rearrange(logits, "b sql v -> (b sql v)")

tensor([2.2000, 0.1000, 1.5000, 0.3000, 0.5000, 1.1000, 1.0000, 0.5000, 0.2000,
        0.2000, 0.9000, 2.2000, 0.1000, 0.4000, 1.5000, 0.3000, 0.3000, 0.1000,
        3.2000, 0.1000, 0.7000, 2.0000, 0.3000, 0.1000, 0.1000, 1.5000, 0.2000,
        3.0000, 0.1000, 0.7000, 0.2000, 0.3000, 0.1000, 1.8000, 2.5000, 2.1000,
        0.2000, 0.2000, 0.3000, 0.9000])